:wind_chime: add user with address entity
groupProjectScale/sweet_city_backend pull request #4
Opened 2023-02-23 23:55 UTC by lisabuilds

- [x] created a user entity together with an address entity using one requestBody.
- [x] next -> create getCurrentParticipants activity controller

2023-02-25 02:21 UTC, multiverse-exploration-kitten requested changes

2023-02-25 02:21 UTC, multiverse-exploration-kitten commented on src/main/java/com/example/controllers/UserController.java
> +        User user = new User();
这里可以用beanutils.copyproperties

2023-02-25 02:21 UTC, multiverse-exploration-kitten commented on src/main/java/com/example/controllers/UserController.java
> +        Address address = new Address();
same here

2023-02-25 02:21 UTC, multiverse-exploration-kitten commented on src/main/java/com/example/model/Address.java
> +    private Integer addressId;
address id 也可以用UUID

2023-02-25 02:21 UTC, multiverse-exploration-kitten commented on src/main/java/com/example/repository/LocationRepository.java
> +                            + ")) < 83000;",
这个 8300 最好可以用variable？ 或许会需要变化的距离搜索？

2023-02-25 02:21 UTC, multiverse-exploration-kitten commented on src/main/java/com/example/services/ActivityService.java
> +        } else {
这个else可以省略

2023-02-25 02:21 UTC, multiverse-exploration-kitten commented on src/main/java/com/example/services/UserService.java
> +        Address address1 = future.get();
这里为什么用async呢？ 

这个future.get()还是blocked，跟没用future的实际效果是一样的

2023-02-26 17:39 UTC, lisabuilds commented on src/main/java/com/example/repository/LocationRepository.java
> +                            + ")) < 83000;",
> 这个 8300 最好可以用variable？ 或许会需要变化的距离搜索？

我把83000 改成了一个final constant，同时加了searchRange param，如果user不传入searchRange，它就会default 83000😊

2023-02-26 17:41 UTC, lisabuilds commented on src/main/java/com/example/controllers/UserController.java
> +        User user = new User();
已经改好了😊

2023-02-26 17:42 UTC, lisabuilds commented on src/main/java/com/example/services/UserService.java
> +        Address address1 = future.get();
对的，我把这个future删了，这个源于我对async in java 并不是很理解。。。

2023-02-26 17:58 UTC, multiverse-exploration-kitten requested changes

2023-02-26 17:58 UTC, multiverse-exploration-kitten commented on src/main/java/com/example/controllers/UserController.java
> +        if (validateAddressDto(userTask.addressDto) == false) {
这个我之前没注意 access一个field一定要用getter

2023-02-26 17:58 UTC, multiverse-exploration-kitten commented on src/main/java/com/example/controllers/UserController.java
> +    public static class UserTask {
这个要用getter和 setter，然后把usertask 单独拎出来。不用写这种nested class

2023-02-26 19:56 UTC, multiverse-exploration-kitten approved these changes

2023-02-26 20:11 UTC, merged